name: Deploy to DockerHub and EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: thoufeek/demoapp
      TAG: latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        cat <<EOF > $HOME/.kube/config
${{ secrets.KUBECONFIG_CONTENT }}
EOF
        chmod 600 $HOME/.kube/config
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deployment/demoapp
      env:
        KUBECONFIG: $HOME/.kube/config
